# fly.toml file generated for viviridian-nixos-nitter on 2022-12-04T12:49:22-08:00

app = "viviridian-nixos-nitter"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "nitter-nixos:fly"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 16969
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "5s"
    interval = "15s"
    restart_limit = 0
    timeout = "15s"

[[services]]
  http_checks = []
  internal_port = 19999
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 19998

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 19999

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
